// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSEStockPrice.Infrastructure.Data;

#nullable disable

namespace SSEStockPrice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311115501_AddColleagueAlert")]
    partial class AddColleagueAlert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSEStockPrice.Models.ColleagueAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColleagueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("ColleagueAlert", (string)null);
                });

            modelBuilder.Entity("SSEStockPrice.Models.SSEPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChangePercent")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SSEPrice", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
